#!/system/bin/sh

. /system/etc/liberty.cfg

if busybox [ $REMOVE_CACHE -eq 1 ]; then
	busybox rm -f /cache/*.apk
	busybox rm -f /cache/*.tmp
	busybox rm -f /data/dalvik-cache/*.apk
	busybox rm -f /data/dalvik-cache/*.tmp
	CACHE_DIR=(` busybox find /data/data -type d -iname *cache* -print `);
	for dir in ${CACHE_DIR[*]}; do
		busybox find $dir -type f -delete
	done
	log -p i -t boot "Cleared data cache..."
fi
