#!/system/xbin/sh

#Defrags database files

VAC_LOG_FILE=/data/S50-vacuum-databases.log

# do nothing if less than 5 days
find $VAC_LOG_FILE -type f -mtime +5 -exec rm '{}' \;

if ! test -f $VAC_LOG_FILE; then

	touch $VAC_LOG_FILE

	busybox mount -o rw,remount /

	if [ -e $VAC_LOG_FILE ]; then
		rm $VAC_LOG_FILE;
	fi;
    	
	echo "Starting Sqlite Vacuum $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $VAC_LOG_FILE;

	for i in \
	`find /data -iname "*.db"`
	do \
		sqlite3 $i 'VACUUM;'; 
		echo Vacuum $i  | tee -a $VAC_LOG_FILE;
	done;

	for i in \
	`find /dbdata -iname "*.db"`
	do \
		sqlite3 $i 'VACUUM;'; 
		echo Vacuum $i  | tee -a $VAC_LOG_FILE;
	done;

	for i in \
	`find /sdcard -iname "*.db"`
	do \
		sqlite3 $i 'VACUUM;'; 
		echo Vacuum $i  | tee -a $VAC_LOG_FILE;
	done

	echo "Sqlite Vacuum finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $VAC_LOG_FILE;

fi
